x-logging: &x-logging
  logging:
    driver: "json-file"
    options:
      max-file: "5"
      max-size: "10m"
services:
  app:
    build: .
    command: ["npm", "run", "dev"]
    env_file:
      - .env.pennywise
    ports:
      - 80:3000
    depends_on:
      - pennywise-redis
      - appwrite
    networks:
      - pennywise
    volumes:
      - .:/app
      - /app/node_modules

  pennywise-redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - pennywise

  traefik:
    image: traefik:2.11
    container_name: appwrite-traefik
    <<: *x-logging
    command:
      - --providers.file.directory=/storage/config
      - --providers.file.watch=true
      - --providers.docker=true
      - --providers.docker.exposedByDefault=false
      - --providers.docker.constraints=Label(`traefik.constraint-label-stack`,`appwrite`)
      - --entrypoints.appwrite_web.address=:80
      - --entrypoints.appwrite_websecure.address=:443
    restart: unless-stopped
    ports:
      - 8080:80
      - 9090:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - appwrite-config:/storage/config:ro
      - appwrite-certificates:/storage/certificates:ro
    depends_on:
      - appwrite
    networks:
      # - gateway
      - appwrite-internal
      - pennywise

  appwrite:
    image: appwrite/appwrite:1.8.1
    container_name: appwrite
    <<: *x-logging
    restart: unless-stopped
    networks:
      - appwrite-internal
    labels:
      - traefik.enable=true
      - traefik.constraint-label-stack=appwrite
      - traefik.docker.network=appwrite-internal
      - traefik.http.services.appwrite_api.loadbalancer.server.port=80
      #http
      - traefik.http.routers.appwrite_api_http.entrypoints=appwrite_web
      - traefik.http.routers.appwrite_api_http.rule=PathPrefix(`/`)
      - traefik.http.routers.appwrite_api_http.service=appwrite_api
      # https
      - traefik.http.routers.appwrite_api_https.entrypoints=appwrite_websecure
      - traefik.http.routers.appwrite_api_https.rule=PathPrefix(`/`)
      - traefik.http.routers.appwrite_api_https.service=appwrite_api
      - traefik.http.routers.appwrite_api_https.tls=true
    volumes:
      - appwrite-uploads:/storage/uploads:rw
      - appwrite-imports:/storage/imports:rw
      - appwrite-cache:/storage/cache:rw
      - appwrite-config:/storage/config:rw
      - appwrite-certificates:/storage/certificates:rw
      - appwrite-functions:/storage/functions:rw
      - appwrite-sites:/storage/sites:rw
      - appwrite-builds:/storage/builds:rw
    depends_on:
      - mariadb
      - redis
    #      - clamav
    env_file:
      - .env.appwrite

  appwrite-console:
    <<: *x-logging
    container_name: appwrite-console
    image: appwrite/console:7.5.7
    restart: unless-stopped
    networks:
      - appwrite-internal
    labels:
      - "traefik.enable=true"
      - "traefik.constraint-label-stack=appwrite"
      - "traefik.docker.network=appwrite"
      - "traefik.http.services.appwrite_console.loadbalancer.server.port=80"
      #ws
      - traefik.http.routers.appwrite_console_http.entrypoints=appwrite_web
      - traefik.http.routers.appwrite_console_http.rule=PathPrefix(`/console`)
      - traefik.http.routers.appwrite_console_http.service=appwrite_console
      # wss
      - traefik.http.routers.appwrite_console_https.entrypoints=appwrite_websecure
      - traefik.http.routers.appwrite_console_https.rule=PathPrefix(`/console`)
      - traefik.http.routers.appwrite_console_https.service=appwrite_console
      - traefik.http.routers.appwrite_console_https.tls=true

  appwrite-realtime:
    image: appwrite/appwrite:1.8.1
    entrypoint: realtime
    container_name: appwrite-realtime
    <<: *x-logging
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.constraint-label-stack=appwrite"
      - "traefik.docker.network=appwrite"
      - "traefik.http.services.appwrite_realtime.loadbalancer.server.port=80"
      #ws
      - traefik.http.routers.appwrite_realtime_ws.entrypoints=appwrite_web
      - traefik.http.routers.appwrite_realtime_ws.rule=PathPrefix(`/v1/realtime`)
      - traefik.http.routers.appwrite_realtime_ws.service=appwrite_realtime
      # wss
      - traefik.http.routers.appwrite_realtime_wss.entrypoints=appwrite_websecure
      - traefik.http.routers.appwrite_realtime_wss.rule=PathPrefix(`/v1/realtime`)
      - traefik.http.routers.appwrite_realtime_wss.service=appwrite_realtime
      - traefik.http.routers.appwrite_realtime_wss.tls=true
    networks:
      - appwrite-internal
    depends_on:
      - mariadb
      - redis
    env_file:
      - .env.appwrite

  appwrite-worker-webhooks:
    image: appwrite/appwrite:1.8.1
    entrypoint: worker-webhooks
    <<: *x-logging
    container_name: appwrite-worker-webhooks
    restart: unless-stopped
    networks:
      - appwrite-internal
    depends_on:
      - redis
      - mariadb
    env_file:
      - .env.appwrite

  appwrite-worker-deletes:
    image: appwrite/appwrite:1.8.1
    entrypoint: worker-deletes
    <<: *x-logging
    container_name: appwrite-worker-deletes
    restart: unless-stopped
    networks:
      - appwrite-internal
    depends_on:
      - redis
      - mariadb
    volumes:
      - appwrite-uploads:/storage/uploads:rw
      - appwrite-cache:/storage/cache:rw
      - appwrite-functions:/storage/functions:rw
      - appwrite-sites:/storage/sites:rw
      - appwrite-builds:/storage/builds:rw
      - appwrite-certificates:/storage/certificates:rw
    env_file:
      - .env.appwrite

  appwrite-worker-databases:
    image: appwrite/appwrite:1.8.1
    entrypoint: worker-databases
    <<: *x-logging
    container_name: appwrite-worker-databases
    restart: unless-stopped
    networks:
      - appwrite-internal
    depends_on:
      - redis
      - mariadb
    env_file:
      - .env.appwrite

  appwrite-worker-builds:
    image: appwrite/appwrite:1.8.1
    entrypoint: worker-builds
    <<: *x-logging
    container_name: appwrite-worker-builds
    restart: unless-stopped
    networks:
      - appwrite-internal
    depends_on:
      - redis
      - mariadb
    volumes:
      - appwrite-functions:/storage/functions:rw
      - appwrite-sites:/storage/sites:rw
      - appwrite-builds:/storage/builds:rw
      - appwrite-uploads:/storage/uploads:rw
    env_file:
      - .env.appwrite

  appwrite-worker-certificates:
    image: appwrite/appwrite:1.8.1
    entrypoint: worker-certificates
    <<: *x-logging
    container_name: appwrite-worker-certificates
    restart: unless-stopped
    networks:
      - appwrite-internal
    depends_on:
      - redis
      - mariadb
    volumes:
      - appwrite-config:/storage/config:rw
      - appwrite-certificates:/storage/certificates:rw
    env_file:
      - .env.appwrite

  appwrite-worker-functions:
    image: appwrite/appwrite:1.8.1
    entrypoint: worker-functions
    <<: *x-logging
    container_name: appwrite-worker-functions
    restart: unless-stopped
    networks:
      - appwrite-internal
    depends_on:
      - redis
      - mariadb
      - openruntimes-executor
    env_file:
      - .env.appwrite

  appwrite-worker-mails:
    image: appwrite/appwrite:1.8.1
    entrypoint: worker-mails
    <<: *x-logging
    container_name: appwrite-worker-mails
    restart: unless-stopped
    networks:
      - appwrite-internal
    depends_on:
      - redis
    env_file:
      - .env.appwrite

  appwrite-worker-messaging:
    image: appwrite/appwrite:1.8.1
    entrypoint: worker-messaging
    <<: *x-logging
    container_name: appwrite-worker-messaging
    restart: unless-stopped
    networks:
      - appwrite-internal
    volumes:
      - appwrite-uploads:/storage/uploads:rw
    depends_on:
      - redis
    env_file:
      - .env.appwrite

  appwrite-worker-migrations:
    image: appwrite/appwrite:1.8.1
    entrypoint: worker-migrations
    <<: *x-logging
    container_name: appwrite-worker-migrations
    restart: unless-stopped
    networks:
      - appwrite-internal
    volumes:
      - appwrite-imports:/storage/imports:rw
    depends_on:
      - mariadb
    env_file:
      - .env.appwrite

  appwrite-task-maintenance:
    image: appwrite/appwrite:1.8.1
    entrypoint: maintenance
    <<: *x-logging
    container_name: appwrite-task-maintenance
    restart: unless-stopped
    networks:
      - appwrite-internal
    depends_on:
      - redis
    env_file:
      - .env.appwrite

  appwrite-task-stats-resources:
    image: appwrite/appwrite:1.8.1
    container_name: appwrite-task-stats-resources
    entrypoint: stats-resources
    <<: *x-logging
    restart: unless-stopped
    networks:
      - appwrite-internal
    depends_on:
      - redis
      - mariadb
    env_file:
      - .env.appwrite

  appwrite-worker-stats-resources:
    image: appwrite/appwrite:1.8.1
    entrypoint: worker-stats-resources
    container_name: appwrite-worker-stats-resources
    <<: *x-logging
    restart: unless-stopped
    networks:
      - appwrite-internal
    depends_on:
      - redis
      - mariadb
    env_file:
      - .env.appwrite

  appwrite-worker-stats-usage:
    image: appwrite/appwrite:1.8.1
    entrypoint: worker-stats-usage
    container_name: appwrite-worker-stats-usage
    <<: *x-logging
    restart: unless-stopped
    networks:
      - appwrite-internal
    depends_on:
      - redis
      - mariadb
    env_file:
      - .env.appwrite

  appwrite-task-scheduler-functions:
    image: appwrite/appwrite:1.8.1
    entrypoint: schedule-functions
    container_name: appwrite-task-scheduler-functions
    <<: *x-logging
    restart: unless-stopped
    networks:
      - appwrite-internal
    depends_on:
      - mariadb
      - redis
    env_file:
      - .env.appwrite

  appwrite-task-scheduler-executions:
    image: appwrite/appwrite:1.8.1
    entrypoint: schedule-executions
    container_name: appwrite-task-scheduler-executions
    <<: *x-logging
    restart: unless-stopped
    networks:
      - appwrite-internal
    depends_on:
      - mariadb
      - redis
    env_file:
      - .env.appwrite

  appwrite-task-scheduler-messages:
    image: appwrite/appwrite:1.8.1
    entrypoint: schedule-messages
    container_name: appwrite-task-scheduler-messages
    <<: *x-logging
    restart: unless-stopped
    networks:
      - appwrite-internal
    depends_on:
      - mariadb
      - redis
    env_file:
      - .env.appwrite

  appwrite-assistant:
    image: appwrite/assistant:0.8.4
    container_name: appwrite-assistant
    <<: *x-logging
    restart: unless-stopped
    networks:
      - appwrite-internal
    env_file:
      - .env.appwrite

  appwrite-browser:
    image: appwrite/browser:0.3.2
    container_name: appwrite-browser
    <<: *x-logging
    restart: unless-stopped
    networks:
      - appwrite-internal

  openruntimes-executor:
    container_name: openruntimes-executor
    hostname: exc1
    <<: *x-logging
    restart: unless-stopped
    stop_signal: SIGINT
    image: openruntimes/executor:0.7.22
    networks:
      - appwrite-internal
      # - runtimes
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - appwrite-builds:/storage/builds:rw
      - appwrite-functions:/storage/functions:rw
      - appwrite-sites:/storage/sites:rw
      # Host mount nessessary to share files between executor and runtimes.
      # It's not possible to share mount file between 2 containers without host mount (copying is too slow)
      - /tmp:/tmp:rw
    env_file:
      - .env.appwrite

  mariadb:
    image: mariadb:10.11 # fix issues when upgrading using: mysql_upgrade -u root -p
    container_name: appwrite-mariadb
    <<: *x-logging
    restart: unless-stopped
    networks:
      - appwrite-internal
    volumes:
      - appwrite-mariadb:/var/lib/mysql:rw
    env_file:
      - .env.appwrite
    command: "mysqld --innodb-flush-method=fsync"

  redis:
    image: redis:7.2.4-alpine
    container_name: appwrite-redis
    <<: *x-logging
    restart: unless-stopped
    command: >
      redis-server
      --maxmemory            512mb
      --maxmemory-policy     allkeys-lru
      --maxmemory-samples    5
    networks:
      - appwrite-internal
    volumes:
      - appwrite-redis:/data:rw

  # clamav:
  #   image: appwrite/clamav:1.2.0
  #   container_name: appwrite-clamav
  #   restart: unless-stopped
  #   networks:
  #     - appwrite-internal
  #   volumes:
  #     - appwrite-uploads:/storage/uploads

networks:
  # Network to isolate Appwrite internal services
  appwrite-internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/24

  # Network with the App + Pennywise Redis + Traefik (Appwrite's load balancer)
  pennywise:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.26.0.0/24

  # gateway:
  #   name: gateway
  # appwrite:
  #   name: appwrite
  # runtimes:
  #   name: runtimes

volumes:
  appwrite-mariadb:
  appwrite-redis:
  appwrite-cache:
  appwrite-uploads:
  appwrite-imports:
  appwrite-certificates:
  appwrite-functions:
  appwrite-sites:
  appwrite-builds:
  appwrite-config:
