import { TransactionRepository } from "@application/ports/repositories/TransactionRepository";import { TransactionContext } from "@application/ports/services/TransactionRunner";import { Transaction } from "@entities/Transaction";import { PostgresDatabaseService } from "@infrastructure/persistence/postgres/client/PostgresDatabaseService";import { UUID } from "node:crypto";
type Row={id:string;workspace_id:string;date:Date;category_id:string;amount:number;notes:string;documentation_url:string}; const map=(r:Row)=>new Transaction(r.id as UUID,r.workspace_id as UUID,new Date(r.date),r.category_id as UUID,r.amount,r.notes,r.documentation_url);
export class PostgresTransactionRepository implements TransactionRepository { constructor(private readonly db: PostgresDatabaseService) {}
async createOne(v:Transaction,tx?:TransactionContext){await this.db.query("insert into transactions (id,workspace_id,date,category_id,amount,notes,documentation_url) values ($1,$2,$3,$4,$5,$6,$7)",[v.id,v.workspaceId,v.date,v.categoryId,v.amount,v.notes,v.documentationUrl],tx)}
async updateOne(v:Transaction,tx?:TransactionContext){await this.db.query("update transactions set workspace_id=$2,date=$3,category_id=$4,amount=$5,notes=$6,documentation_url=$7 where id=$1",[v.id,v.workspaceId,v.date,v.categoryId,v.amount,v.notes,v.documentationUrl],tx)}
async getOneById(transactionId:UUID,tx?:TransactionContext){const r=await this.db.query<Row>("select * from transactions where id=$1",[transactionId],tx);return r.rows[0]?map(r.rows[0]):undefined}
async deleteManyByWorkspaceId(workspaceId:UUID,tx?:TransactionContext){await this.db.query("delete from transactions where workspace_id=$1",[workspaceId],tx)}
async includesCategory(categoryId:UUID,tx?:TransactionContext){const r=await this.db.query<{count:string}>("select count(*)::text as count from transactions where category_id=$1",[categoryId],tx);return Number(r.rows[0]?.count||0)>0}
async deleteOneById(transactionId:UUID,tx?:TransactionContext){await this.db.query("delete from transactions where id=$1",[transactionId],tx)}
async getManyByWorkspaceId(workspaceId:UUID,tx?:TransactionContext){const r=await this.db.query<Row>("select * from transactions where workspace_id=$1",[workspaceId],tx);return r.rows.map(map)}
async getCategoryTotalsForMonth(workspaceId:UUID,year:number,month:number,tx?:TransactionContext){const r=await this.db.query<{category_id:string;total:number}>("select category_id, coalesce(sum(amount),0)::float as total from transactions where workspace_id=$1 and extract(year from date)=$2 and extract(month from date)=$3 group by category_id",[workspaceId,year,month],tx);return r.rows.map((v: { category_id: string; total: number }) => ({ categoryId: v.category_id as UUID, total: v.total }))} }
